version: '2'

services:
  golang:
    build: .
    environment:
      - HBASE_HOST=hbase
    volumes:
      - .:/src/go
      - $GOPATH/pkg/mod:/go/pkg/mod
    ports:
      - 80:8080
    working_dir: /src/go
    command: go run main.go

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   expose:
  #     - "2181"
  #   logging:
  #       driver: "none"

  # hbase:
  #   image: pierrezemb/hbase-docker:standalone-1.3.1
  #   links:
  #     - zookeeper
  #   logging:
  #     driver: "none"
  #   volumes:
  #     - ./hbase-data:/hbase-data  
  #   ports:
  #     - "16010:16010"
  #   expose:
  #     - "8080"
  #     - "9090"
  #     - "16000"
  #     - "16010"
  #     - "16020"
  #     - "16030"
  #   command: ["/wait-for-it.sh", "zookeeper:2181", "-t", "10", "--", "/usr/bin/supervisord"]

  hbase:
    image: harisekhon/hbase:2.1
    volumes:
      - ./hbase-data:/hbase-data
    ports:
      - 2181:2181
      - 8080:8080
      - 8085:8085
      - 9090:9090
      - 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301

  hue:
    image: gethue/hue
    volumes:
      - ./hue.ini:/hue/desktop/conf/hue.ini
    ports:
      - 8888:8888
    depends_on:
      - hbase

  # cloudera:
  #   image: cloudera/quickstart:latest
  #   privileged: true
  #   hostname: quickstart.cloudera
  #   command: /usr/bin/docker-quickstart
  #   ports:
  #     - "8020:8020"   # HDFS 
  #     - "8022:22"     # SSH
  #     - "7180:7180"   # Cloudera Manager
  #     - "8888:8888"   # Hue
  #     - "11000:11000" # Oozie
  #     - "50070:50070" # HDFS Rest Namenode
  #     - "50075:50075" # HDFS Rest Datanode
  #     - "2181:2181"   # Zookeeper
  #     - "8088:8088"   # YARN Resource Manager
  #     - "19888:19888" # MapReduce Job History
  #     - "50030:50030" # MapReduce Job Tracker
  #     - "8983:8983"   # Solr
  #     - "16000:16000" # Sqoop Metastore
  #     - "8042:8042"   # YARN Node Manager
  #     - "60010:60010" # HBase Master
  #     - "60030:60030" # HBase Region
  #     - "9090:9090"   # HBase Thrift
  #     - "8080:8080"   # HBase Rest
  #     - "7077:7077"   # Spark Master
  #   tty: true
  #   stdin_open: true
  #   volumes: 
  #     - /var/shared_cloudera_quickstart:/media/shared_from_local 